### ISSUE TITLE
No post ID in Report's breadcrumb

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1007]
```
<div id="brdmain">
                <div class="btn-group btn-breadcrumb">
    <a class="btn btn-primary" href="index.php"><span class="glyphicon glyphicon-home"></span></a>
    <a class="btn btn-primary" href="viewforum.php?id=1">Announcements</a>
    <a class="btn btn-primary" href="viewtopic.php?pid=#p">Test</a>
    <a class="btn btn-primary" href="#">Report post</a>
</div>
```

**Comment by Studio384** [comment]
I'm unable to reproduce. If I report a post, I get this as link:

'''
http://localhost/modern36/viewtopic.php?pid=1#p1
'''

**Comment by oldhobbyist** [comment]
@quy is probably looking at the source (html generated) where the report button is on?

**Comment by Quy** [comment]
In `misc-report.tpl.php`, `$is` is undefined.
`<a class="btn btn-primary" href="viewtopic.php?pid=<?php echo $id ?>#p<?php echo $id ?>"><?php echo luna_htmlspecialchars($cur_post['subject']) ?></a>`
