### ISSUE TITLE
Thread.php will load even without permission

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1060]

**Comment by Quy** [comment]
To clarify, the quickpost form and the Post button are displayed to groups without posting permission.

**Comment by Quy** [comment]
Don't forget the Post button too.

**Comment by Studio384** [comment]
Do you mean the post button in the forum overview? There is no post button in the topic view.

**Comment by Quy** [comment]
At getluna.org. Log out. Go to the Announcements forum. There is a Post button. Here is the HTML code: `<a class="btn btn-default" href="post.php?fid=1">Post</a>`
