### ISSUE TITLE
Icon issue in topic view navbar

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1106]
So we have this weird issue with the navbars icons in the forum view and post view for Inbox. If anyone has an idea on how to fix this, or why this happens in the first place, be my guest, I've tried to search everywhere, and couldn't find it...

You can see the bug here in the navbar: http://forum.getluna.org/viewtopic.php?id=714 (you have to be logged in to see the issue).

@Quy, perhaps you can help me further?

**Comment by Quy** [comment]
I see the search icon display issue but I am not see what you are referring to. Please attach screenshot.

**Comment by Studio384** [comment]
![correctmain](https://cloud.githubusercontent.com/assets/1693592/6682175/77ff1786-cc74-11e4-9225-da6897c26dfa.PNG)
Above, this is how the navbar is supposed to look, and the way it looks on prety much all of our pages.

![wrong](https://cloud.githubusercontent.com/assets/1693592/6682178/7808409a-cc74-11e4-9bf8-17194aa8bfac.png)
Howerver, this is how the navbar looks in the topic view and when posting or editing a post/PM. For some reason, the Font Awesome icons seem to lose their hight.

![withoutstylewrong](https://cloud.githubusercontent.com/assets/1693592/6682177/7806b252-cc74-11e4-9b9c-61b121aa0c0a.PNG)
The issue doesn't seem to be in the themes of Luna, as it also appears, as seen above, when only the Bootstrap and Font Awesome styles are in affect. And the issue is still not there in other pages:
![withoutstylecorrect](https://cloud.githubusercontent.com/assets/1693592/6682176/780694de-cc74-11e4-9e5c-f486a94eb1d0.PNG)

Do you have any idea why this happens?

**Comment by Quy** [comment]
It is because of the JavaScript code not being in the `<head></head>` tags.
```
<script type="text/javascript">
/* <![CDATA[ */
function process_form(the_form) {
	var required_fields = {
		"req_message": "Message",
		"req_subject": "Subject"
	};
	if (document.all || document.getElementById) {
		for (var i = 0; i < the_form.length; ++i) {
			var elem = the_form.elements[i];
			if (elem.name && required_fields[elem.name] && !elem.value && elem.type && (/^(?:text(?:area)?|password|file)$/i.test(elem.type))) {
				alert('"' + required_fields[elem.name] + '" is a required field in this form.');
				elem.focus();
				return false;
			}
		}
	}
	return true;
}
/* ]]> */
</script>
<!DOCTYPE html>
<html>
	<head>
```

**Comment by Studio384** [comment]
Might explain why this only happens on pages with textareas... :) Anyway, thanks, I'll look into it.

**Comment by Studio384** [comment]
Thanks for the help. Can't believe I didn't notice that. It's fixed. Finally.
