### ISSUE TITLE
New Post - Undefined variables

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1130]
Notice: Undefined variable: message in C:\xampp\htdocs\projects\Luna\themes\Luna\post.php on line 22

Notice: Undefined variable: pin_active in C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 63

Notice: Undefined variable: pin_status in C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 63

**Comment by Studio384** [comment]
You realy don't want me to work on that documentation, do you? :package: 

Seriously through, thanks for reporting all things you've reported so far, and thanks for anything that is coming already. Keep going.

**Comment by Quy** [comment]
:smile: You're welcome!
