### ISSUE TITLE
Notifications - passing id in query string

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1140]
Admins cannot view users' notifications. Why is the id in the query string? 
`http://localhost/projects/luna/notifications.php?id=5`

**Comment by Studio384** [comment]
This is on purpose, I think there is no point to admins being able to see others their notifications. For now, it is only when someone makes a response on a topic that that user was subscribed too, or when the board is updated.

**Comment by Quy** [comment]
In that case, use `$luna_user['id']` and remove the id from the query string.

**Comment by Studio384** [comment]
I've altered the page's behavior to use the ```$Luna_user['id']``` for queries, when no id is set in the URL, it will show the current user's notifications.

**Comment by Quy** [comment]
In `me_functions.php`, remove `?id=<?php echo $id ?>`.
`		<a class="<?php if ($page == 'notifications') echo 'active'; ?> list-group-item" href="notifications.php?id=<?php echo $id ?>"><?php echo $lang['Notifications'] ?></a>`

**Comment by Quy** [comment]
In `header.php`, remove from `id` query string:
`$ind_notification[] = '<li><a href="notifications.php?id='.$luna_user['id'].'">No new notifications</a></li>';`
`<li><a class="pull-right" href="notifications.php?id='.$luna_user['id'].'">More <i class="fa fa-fw fa-arrow-right"></i></a></li>`
`$notification_menu_item = '<li><a href="notifications.php?id='.$luna_user['id'].'">'.$notificon.'<span class="visible-xs-inline"> '.$lang['Notifications'].'</span></a></li>';`
