### ISSUE TITLE
Ban admin

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1142]
```
Notice: Constant FORUM_ACTIVE_PAGE already defined in C:\xampp\htdocs\projects\Luna\backstage\bans.php on line 86

Fatal error: Cannot redeclare load_admin_nav() (previously declared in C:\xampp\htdocs\projects\Luna\include\backstage_functions.php:11) in C:\xampp\htdocs\projects\Luna\include\backstage_functions.php on line 193
```

**Comment by Studio384** [comment]
Can you tell me where you get these errors? I fail to recreate them.

**Comment by Quy** [comment]
In `include\common.php`, change as follows: `error_reporting(E_ALL)`
Log in to your account as an admin. 
Under Profile>Settings>Admin, click Ban user button.

**Comment by Studio384** [comment]
Oh, ban an admin you ment (I tried it with a normal account). Ok, will get fixed.
