### ISSUE TITLE
Undefined index: visible

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1145]
`PHP Notice:  Undefined index: visible in C:\xampp\htdocs\projects\Luna\backstage\menu.php`

**Comment by Studio384** [comment]
Where does this error appear? I can't reproduce this one either.

**Comment by Quy** [comment]
Under Settings>Menu, disable a menu and click Save.

**Comment by Studio384** [comment]
I'm not seeing it, I don't get any errors.

**Comment by Quy** [comment]
It is in the error log. When `Show` is not checked, `visible` is not set in `$_POST['item']`.
