### ISSUE TITLE
Field focus and tab order

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1176]
When posting, the field focus should start with Subject and then Message, but now there is no focus and tabbing from Subject goes to the toolbar.

**Comment by Quy** [comment]
Tabbing from Subject still does not go to Message. Make sure to apply this to Edit, and Inbox.

**Comment by Studio384** [comment]
O, I tested it with quick post... Reopening again.

**Comment by Quy** [comment]
and Send email.

**Comment by Studio384** [comment]
Weird, from subject to message, they both have the next tab_index, yet it skips message and goes straight to the newest user in the footer... Any ideas?

**Comment by Gama101** [comment]
For me its working good. Im using FF 38 and Luna 0.9.4214.

When i have selected subject field and im pressing tab - it goes to message field.

**Comment by Quy** [comment]
Don't start tabindex with 0 value.

**Comment by Quy** [comment]
and edit.php

**Comment by Quy** [comment]
It would be nice too for the login modal.

**Comment by Studio384** [comment]
The login modal already has this and the behavior here is correct (unless you're experiencing issues on a specific page?).

**Comment by Quy** [comment]
Sorry I meant autofocus on the Username.
