### ISSUE TITLE
Email returns a blank page

### ISSUE THREAD

**Issue by Sortova** [GetLuna/Luna#1178]
When sending an e-mail, the webUI will return a blank page and generate the following log (Luna 0.7.0):

PHP Fatal error:  Call to undefined function luna_mail() in /var/www/html/forum/new_inbox.php on line 257, referer: https://luna.example.com/forum/new_inbox.php

The following patch will fix it.

$ diff new_inbox.php.org new_inbox.php
<pre>
11a12
> require FORUM_ROOT.'include/email.php';
-bash-4.1$ diff -p new_inbox.php.org new_inbox.php
*** new_inbox.php.org	2015-04-04 09:08:17.174438628 -0500
--- new_inbox.php	2015-04-04 09:07:54.642815980 -0500
***************
*** 9,14 ****
--- 9,15 ----
  define('FORUM_ROOT', dirname(__FILE__).'/');
  require FORUM_ROOT.'include/common.php';
  require FORUM_ROOT.'include/inbox_functions.php';
+ require FORUM_ROOT.'include/email.php';
  
  // No guest here !
  if ($luna_user['is_guest'])
</pre>

**Comment by Studio384** [comment]
Thanks, the fix will be included in the RC2 build.
