### ISSUE TITLE
No access to backstage

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1180]
```
Notice: Constant FORUM_ACTIVE_PAGE already defined in C:\xampp\htdocs\projects\Luna\backstage\settings.php on line 134

Fatal error: Cannot redeclare load_admin_nav() (previously declared in C:\xampp\htdocs\projects\Luna\include\backstage_functions.php:11) in C:\xampp\htdocs\projects\Luna\include\backstage_functions.php on line 193
```

**Comment by Studio384** [comment]
I guess this is when you access the Backstage when you do not have permission to view the Backstage? Anyway, the Backstage will now behave different for this, in RC2, it will redirect you to the login screen.

**Comment by Quy** [comment]
`bans.php` and `loader.php` need to be fixed.

**Comment by Studio384** [comment]
What's the issue with loader.php, seems fixed to me, it redirects to the correct page.
