### ISSUE TITLE
More consistent font stacks in default and backstage

### ISSUE THREAD

**Issue by ListenerJubatus** [GetLuna/Luna#1190]
I have a Windows 8 PC and a Mac. Presumably, the Mac doesn't have the full Segoe UI font family, meaning that the Backstage is rendered in glorious Times New Roman.

Yet, the default forum theme does have Arial as a fallback, but just Arial. It's a little inconsistent. I'd personally go Segoe UI Light, Helvetica, Arial, sans-serif.

Or, Roboto as a web font; especially given that your default style actually does sort of look a little Android-ish, and it's got a whole suite of styles.

**Comment by Studio384** [comment]
But I love Times New Roman. :stuck_out_tongue:

I'll change it to be more consistent.

**Comment by Studio384** [comment]
Try out the latest update, in case Segoe UI can't be found, it will now use Open Sans from the web (and if that fails Helvetica, Arial, sans-serif). Better now? I don't have a Mac to test.
