### ISSUE TITLE
Hide Inbox in profile nav when inbox disabled

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1198]
When inbox is disabled, the Inbox link in profile nav should also be disabled.

**Comment by Studio384** [comment]
This is already the case as of commit 5ef2d4f676ffa094fc0247f01a6919623ab4d0c1.

**Comment by Quy** [comment]
Not the profile side nav.
```
Profile
Inbox
Notifications
Settings
```

**Comment by Quy** [comment]
Also, hide it if user has disabled PM.

**Comment by Studio384** [comment]
Yep, noticed it when updating my own board... Will get to it.
