### ISSUE TITLE
Unable to register new user on 0.8

### ISSUE THREAD

**Issue by Sortova** [GetLuna/Luna#1202]
Upgraded from 0.7 to 0.8 on Saturday morning. Now unable to register new users. The option is checked in Backstage to allow for new users to register.

I can get through the form, but when I hit "Register" I get the error:

An error was encountered
Error: Unable to create user.

This is the URL: /register.php?action=register

Did the database schema change between versions? The only thing that changed in register.php was the "elseif" to an "if". I put it back just to check but it didn't help.

My guess is that if a field was added to the DB then the post doesn't work. I haven't investigated it more deeply, but if I find anything I'll post it here.

**Comment by Sortova** [comment]
Hrm - I enabled logging and for some reason timezone was set as null, thus the insert failed. I went ahead and set the timezone to US Eastern (-5) and now registration works again.

**Comment by Studio384** [comment]
I'm able to create a new user on a fresh installation. Do you know why the timezone got to NULL? This might be an issue in the settings, but I can't find a reason why it would switch to NULL.

**Comment by Sortova** [comment]
Beats me. I just did an upgrade on Saturday morning but it wasn't until this morning that someone tried to register. The time zones under settings was set to Greenwich Mean Time so I set it to Eastern US and it started working.

I turned on MySQL logging and saw that the timezone field in the INSERT was empty. Wish I could be of more help.
