### ISSUE TITLE
Add tooltip to sticky button

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1210]
It may not be obvious that the green pin button is a sticky button. Add a tooltip to it.
Also, what does the microphone button do?

**Comment by Studio384** [comment]
Mute posting. When you edit a post and that button is enabled, it won't show "Last edited..."

I'll add a tooltip to both.

**Comment by Gama101** [comment]
I don't know if i've done somehing wrong but this tooltip over these elements are dsiplayed as standard title - not jquery one. 
![bez-nazwy-1](https://cloud.githubusercontent.com/assets/1129947/7045001/a6be1824-ddf9-11e4-9356-c1d039e4f696.png)

**Comment by Studio384** [comment]
That's what is supposed to happen.
