### ISSUE TITLE
Restore options - No file was uploaded warning

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1211]
Even though a file was selected/uploaded, I still get this warning:
`No file was uploaded or the upload failed, the database was not restored.`

**Comment by Studio384** [comment]
You have any idea why this happens? I would love to get the fix for this into 1.0.0, but can't find it and my time before I leave is running out.

**Comment by Quy** [comment]
Changed `$HTTP_POST_FILES` to `$_FILES` fixed it for me.

**Comment by Studio384** [comment]
Ho... depricated feature... Of course.
