### ISSUE TITLE
Check out the SummerNote editor

### ISSUE THREAD

**Issue by axisdos** [GetLuna/Luna#1218]
Hey, if you can't fully integrate other Post Editor to Luna, you can check out Summernote, a simple WYSIWYG Editor using Bootstrap. I hope this one is the best fit https://github.com/summernote/summernote

**Comment by Studio384** [comment]
I'm currently investigating another editor. Check out the fb_editor branch later (it now only has the normal Luna code in it). More info soon.

**Comment by Studio384** [comment]
We're looking into another editor, as said before, therefor I'll close this issue.
