### ISSUE TITLE
Use language string

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1224]
`<a href="register.php" class="navbar-brand"><span class="fa fa-fw fa-user"></span> Register</a>`

PS: Please don't close this ticket yet as there maybe more.

**Comment by Quy** [comment]
`<h2 style="margin-top: 60px;">We've got us a situation here</h2>`

**Comment by Quy** [comment]
`<input class="form-control" type="text" name="keywords" placeholder="Search in posts" maxlength="100" />`

**Comment by Quy** [comment]
`<?php echo forum_number_format($user_data['num_posts']) ?> posts since <?php echo format_time($user_data['registered'], true) ?>`

**Comment by Quy** [comment]
`<label class="col-sm-3 control-label">Avatar<span class="help-block"><?php echo $lang['Avatar info'] ?></span></label>`

**Comment by Quy** [comment]
`<label class="col-sm-3 control-label">Signature<span class="help-block"><?php echo $lang['Signature info'] ?></span></label>`

**Comment by Quy** [comment]
`		<h3><?php echo $lang['New notifications'] ?><span class="pull-right"><a href="notifications.php?id=2&action=readnoti" class="btn btn-primary"><span class="fa fa-fw fa-eye"></span> Mark as seen</a></span></h3>`

`		<h3><?php echo $lang['Seen notifications'] ?><span class="pull-right"><a href="notifications.php?id=2&action=delnoti" class="btn btn-danger"><span class="fa fa-fw fa-trash"></span> Delete notifications</a></span></h3>`

**Comment by Studio384** [comment]
In case you might run into the About.php page, that is intentional. Thanks for reporting.

**Comment by Studio384** [comment]
This commit should fix everything reported so far, I'll leave this ticket open for other reports of missing strings until 13 April.

**Comment by Quy** [comment]
`<input type="text" class="form-control" name="name" placeholder="Name" value="" />`

`<input type="text" class="form-control" name="url" placeholder="URL" value="" />`

**Comment by Quy** [comment]
`echo 'This theme has no settings available...';`

**Comment by Quy** [comment]
`echo '<a class="btn btn-primary disabled">In use</a>';`

**Comment by Quy** [comment]
`<h2 class="profile-settings-head">Settings<span class="pull-right"><button class="btn btn-primary" type="submit" name="update"><span class="fa fa-fw fa-check"></span> <?php echo $lang['Save'] ?></button></span></h2>`

**Comment by Quy** [comment]
`<a href="help.php" class="navbar-brand"><span class="fa fa-fw fa-info-circle"></span> Help</a>`

**Comment by Quy** [comment]
`<title>Backstage</title>`

**Comment by Quy** [comment]
`<a href="#" data-toggle="modal" data-target="#login-form" data-dismiss="modal">Back</a>`

**Comment by Quy** [comment]
`<a href="search.php" class="list-group-item">Search the board</a>`

**Comment by Quy** [comment]
`<label class="col-sm-3 control-label"><?php echo $lang['Send to'] ?><span class="help-block">Separate names with commas, maximum <?php echo ($luna_config['o_pms_max_receiver']-1) ?> names</span></label>`

**Comment by Quy** [comment]
`<input type="submit" class="btn btn-danger" name="soft_delete" value="Soft delete" />`

**Comment by Quy** [comment]
`		<h2>Edit "<?php echo luna_htmlspecialchars($cur_post['subject']) ?>"</h2><span class="pull-right"><a class="btn btn-danger" href="viewtopic.php?id=<?php echo $cur_post['tid'] ?>"><span class="fa fa-fw fa-chevron-left"></span> Cancel</a></span>`

**Comment by Quy** [comment]
```
		<?php if ($fid) { ?>
			<h2><?php printf($lang['New topic in'], luna_htmlspecialchars($cur_posting['forum_name'])) ?></h2><span class="pull-right"><a class="btn btn-danger" href="index.php?id=<?php echo $cur_posting['id'] ?>"><span class="fa fa-fw fa-chevron-left"></span> Cancel</a></span>
		<?php } else { ?>
			<h2><?php printf($lang['New comment in'], luna_htmlspecialchars($cur_posting['subject'])) ?></h2><span class="pull-right"><a class="btn btn-danger" href="viewtopic.php?id=<?php echo $cur_posting['id'] ?>"><span class="fa fa-fw fa-chevron-left"></span> Cancel</a></span>
		<?php } ?>
```

**Comment by Quy** [comment]
`$ind_notification[] = '<li><a href="notifications.php">No new notifications</a></li>';`

**Comment by Quy** [comment]
`<input type="submit" class="btn btn-danger" name="soft_delete" value="Soft delete" />`

`<input type="submit" class="btn btn-primary" name="reset" value="Reset post" />`

**Comment by Quy** [comment]
`<input type="submit" class="btn btn-primary btn-block" value="Login" />`

**Comment by Quy** [comment]
`<h3 class="panel-title">Moderate content</h3>`

**Comment by Quy** [comment]
Don't know if you want to translate `Copyright`.
`echo 'Copyright &copy; '.date('Y').' &middot; '.$luna_config['o_board_title'];`

**Comment by Quy** [comment]
`<h2>Moderating "<?php echo luna_htmlspecialchars($cur_forum['forum_name']) ?>"</h2><span class="pull-right"><?php echo $paging_links ?></span>`

**Comment by Quy** [comment]
`<label class="col-sm-3 control-label">Parent section</label>`
`<option value="0">No parent forum selected</option>`

**Comment by Quy** [comment]
I am done with this ticket. :thumbsup:

**Comment by Studio384** [comment]
Thanks for your work.
