### ISSUE TITLE
Color Schemes improvements

### ISSUE THREAD

**Issue by CaerCam** [GetLuna/Luna#1238]
Backstage Color Schemes could be handled differently, by using a custom CSS file − say accents.css − in the theme's folder. This file could be generated easily since color schemes only have 3 different colors, and a simple class added to the `<body>` tag − say `body.cs-luna` for instance − would trigger the color scheme instead of injecting the styling properties directly in the header. Main advantage of this, apart from catching and easiness in adding/removing color schemes, is that users would then be able to preview each color scheme when selecting it in their profile, instead of having to save it: a tiny JavaScript switching the body class to the select color scheme will do the job.

I just tested locally, I get a 25kb minified CSS file for the Luna color schemes. I like that behavior in WordPress' Dashboard, it could be a nice user-friendly tweak.

**Comment by Studio384** [comment]
Check the fb_accent branch for improvements to this. Backstage accents will also be developed in this branch.
