### ISSUE TITLE
Userlist - Avatars not default dimensions don't line up / digits after the year?

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1239]
https://www.dropbox.com/s/si1hgtj8qytys68/userlist.jpg?dl=0

**Comment by ListenerJubatus** [comment]
http://trotmania.ponyvillefm.com/forum/viewtopic.php?pid=107#p107

Confirmed by one of my users. The default/placeholder avatar is 100x100, but our sizes can go up to 120x120.

**Comment by Studio384** [comment]
Indeed something we should force to have a width and height of 100 pixels for the image to be displayed in. Thanks for reporting.
