### ISSUE TITLE
Using gettext for translations

### ISSUE THREAD

**Issue by CaerCam** [GetLuna/Luna#1240]
How about switching to gettext to handle the translation part?

**Comment by CaerCam** [comment]
Started working on it, looking good! Very similar to WordPress (same .po/.mo file handling library) so it will be easy for people to translate the forum using Poedit. I updated the whole source code to get rid of `$lang` and use `__()`/`_e()` instead, now I just need to take care of the database/user part :)

**Comment by Studio384** [comment]
I suppose you get this done for Luna 1.1?

In another question, do you mind if I add you to the developer group here on GitHub so that I can assign the tickets you're working on to you?

**Comment by CaerCam** [comment]
Yep, should be good for 1.1.

Thanks for the invite, joined!

**Comment by Studio384** [comment]
Luna 1.1 is becoming the updated I didn't wanted it to be. It was supposed to be a small update that mainly focussed on some of the new changes from Aero. Instead, we're heading for a new way of translating Luna, nonces, a major change to the notification system, etc.

You have a bad influence on my roadmaps... A good bad influence, that is.

**Comment by CaerCam** [comment]
Ha, yeah, sorry about that! We can postpone some parts if you'd rather, the gettext implementation is rather a heavy one and could easily be scheduled for a later version.

As for the rest, well, I'm in the process of switching my board from FluxBB to Luna, what I proposed here are things I will built eventually for my own forum, so I may as well submit it to you rather than doing it on my side only :)

**Comment by Studio384** [comment]
Nha, no need to postpone stuff that has been made.
