### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1246]
There is a major flaw in the design of an aweful lot of things out there: the designs only work great during night or day. And let's be honest: you can't create a design that works good in both situations.

When it is day, a bright interface is easier to use and easier for your eyes. At night, that very same design will "burn" your eyes. The interface should be darker. Bittersweet Shimmer should allow users to enable a "night mode" that makes the theme switch to a darker interface.

- The option is part of the Luna Core, but themes have to support it
- It's disabeld by default, but can be enabled permanenlty or only during night hours
- Luna and Sunrise will have support for the night setting, Random 5.0 not (at least, it's not planned to have support for it, Random 5.1 will)

**Comment by Quy** [comment]
Text color not readable:
https://www.dropbox.com/s/z9jmat15p4g1eu7/night1.jpg?dl=0
https://www.dropbox.com/s/ykvr2wb8hxjckro/night2.jpg?dl=0

**Comment by Studio384** [comment]
I'll work on it. Thanks for reporting.
