### ISSUE TITLE
Include Lunicons 0.0.0

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1251]
Lunicons is a font that is currently in development for Luna 1.1. However, we've a extremely early version ready that contains to Luna logo. The plan with this is to replace Font Awesomes moon-o icon to match the actual Luna logo. Further extension to the font will be added in later version, for more, please go to our Lunicons repository.

**Comment by Quy** [comment]
Update this?
`new_notification('2', 'backstage/about.php', 'Welcome to Luna, discover the possibilities!', 'fa-moon-o');`
