### ISSUE TITLE
confirm_referrer() error (duplicate '/')

### ISSUE THREAD

**Issue by CaerCam** [GetLuna/Luna#1254]
I observed this on my local server but didn't paid much attention, but I just registered on the official forum at forum.getluna.org and got the same error.

`confirm_referrer()` create a duplicate slash in URL that results in testing referrer against `http://domain.ltd//index.php`, which of course never works. `get_base_url().'/'.$script` (`include/functions.php`, line 1174) should be cleaned: a simple `rtrim( get_base_url(), '/\\' ) . '/' . $script` should do the trick.

**Comment by Studio384** [comment]
Thanks for providing this fix.

**Comment by CaerCam** [comment]
Not that good a fix actually, I bumped into the issue once again.

The previous fix is incomplete as, even though we should make sure we don't duplicate the slash at the end of the base url, there can still be duplicates in the script value. This should be better:

	$valid = parse_url(strtolower(rtrim(get_base_url(), '/\\').'/'.ltrim($script, '/\\')));

A simplification would be to transfer the `rtrim()` into the `get_base_url()` function, to make it certain we get a base url with a trailing slash.

**Comment by Studio384** [comment]
Aplied your fix once again, I'll alter ```get_base_url()``` in Bittersweet Shimmer to handle ```rtrim()``` itselfs. Thanks for the fix once again.
