### ISSUE TITLE
Provide data-only for built-in menus

### ISSUE THREAD

**Issue by CaerCam** [GetLuna/Luna#1256]
I'm building a custom theme and it's a real problem to use built-in menu such as the user menu (inbox - notifications - user) as it already is completely hardcoded, requiring a complete custom rewrite. There should two ways to handle this kind of menu: pure data, providing an array of needed element (URLs, titles, additional data such as number of notifications, etc) and pure display, rendering a standard HTML code.

This is confusing as even though I get the need for a default menu display, it messes with the freedom given to the themes.

**Comment by Studio384** [comment]
In Aero, we've split of a major part of the core from Bootstrap, not everything got so far, even some of the new parts. We're working on improving this for Bittersweet Shimmer and future releases like Cornflower Blue, I hope we can update this for you in the coming release.

**Comment by Studio384** [comment]
Done

**Comment by Studio384** [comment]
In Luna 2.1 we will already take a look at theme's capability of expanding Luna, although the big work on this will still be done for Luna 3.
