### ISSUE TITLE
More than 1 user in notifications table

### ISSUE THREAD

**Issue by xQuByte** [GetLuna/Luna#1269]
Hello,
Proposes that in the database table "notifications" in "user_id" could give more than one user. Eg. "User_id" => "1,2,54,33,66,33"

For sure with time it will be necessary. 
(For my extensions :) )
Yours!

**Comment by CaerCam** [comment]
Not sure that's good idea: how do you plan to handle users deleting/marking their notifications as read?

**Comment by xQuByte** [comment]
I had not thought about it. You're right. This is a bad idea.

**Comment by Studio384** [comment]
This is a bad idea for multiple reasons, one stated by CaerCam. It's better to just loop through the new notification function for every user, as Luna 1.0 does now.
