### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by ninjagolloyd** [GetLuna/Luna#1275]
So,  sometimes for random reasons, people get an error that says "Unable to fetch topic list." What is this? Is it Luna or the DB? Try it now on forum.getluna.org .

**Comment by Studio384** [comment]
Can you give me an example of which page and wheter or not you're logged in?

**Comment by rolfpancake** [comment]
Well I think he means that your forum at http://forum.getluna.org/ is not reachable at the moment. I'm not able to login on the site and just get the following error:

An error was encountered
Error: Unable to fetch topic list.

**Comment by Studio384** [comment]
Ho, well it worked for me because I was already logged in, anyway, isn't a bug, simply didn't upload all files.

**Comment by ninjagolloyd** [comment]
OK. Thanks!
