### ISSUE TITLE
Moderator should not has a full access in the Backstage

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1284]
I am testing developer branch and I have seen that moderator has full control in Backstage. It should be fixed.

**Comment by ninjagolloyd** [comment]
Go into the backstage. Click users. Click groups. Edit moderators however you like, or make a new group. 

**Thank you!**

**Comment by Studio384** [comment]
Thanks for reporting. I'll issue a new release as soon as this security issue is fixed!
