### ISSUE TITLE
Messages should be marked as read after... read.

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1285]
Looks like this function does not work. I have read test message but forum still says that I have new message.

**Comment by ninjagolloyd** [comment]
You mark them yourself. Only unseen notifications pop up in the fly out, so you can mark them yourself.

**Comment by kaaleth** [comment]
But this way is really uncomfortable. It should works automatically.

**Comment by Studio384** [comment]
At my end, it's marked as read as soon as I've read it, do you have any more details on when this happens?

**Comment by kaaleth** [comment]
I have created two different accounts at my localhost and sent a test message from X to Y. The Y user has received and read X's message but forum still shows alert that I have one new item. System does not mark the message as read, so I have to do this manually - so I select message and click on "mark as read" button.

Does it work properly?

**Comment by ninjagolloyd** [comment]
Oh. What DB is that?

**Comment by kaaleth** [comment]
DB? MySQL.

**Comment by ninjagolloyd** [comment]
O.o your thing is messed up.

**Comment by kaaleth** [comment]
@Studio384

The same issue I can meet at official luna forum
