### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1286]
I have noticed that Luna has missing some translation strings.

My note:

Register
- [x] "The email address you entered is invalid"

Forum view
- [x] "Post topic" button,

Topic view
- [x] "on" on the bar with user's details (e.g. by kaaleth **ON** today 3:06),

Search engine
- [x] "You have to enter at least one keyword and/or an author to search for.",

Notification & messages
- [x] "More" button in notification panel,

User profile
- [x] "Send mail" button (doubled),
- [x] "Show topics" button,,
- [x] "Show posts" button,
- [x] "Show subscriptions" button,
- [x] "No signature currently stored in profile.",
- [x] "Upload avatar" button,
- [x] "BackstageColor" corrupted (looks like two diffrent strings),
- [x] ~~Some positions in timezone looks weird, for example Eastern, Mountain, Central, Eastern (I think there should be examples like USA, Brazil),~~ Luna 2.0
- [x] no strings for nightmode options, "Never use night mode", "Always use night mode" ...
- [x] ... and the 3rd radio box is blank (blank space),
- [x] "You must select some messages",
- [x] "The selected file was too large to upload. The server didn't allow the upload."
- [x] "Signatures cannot be longer than" {value} "characters. Please reduce your signature by" {value } "characters."
- [x] "The website URL you entered is invalid."
- [x] "Administrators cannot be deleted. In order to delete this user, you must first move him/her to a different user group." - exists as string but is no working,
- [x] "This user is currently not subscribed to any topics."
- [x] "Unverified" - (disabed email button),

Backstage
- [x] There are "Announcement title", "Announcement type", "Announcement message" strings but after translation they are still in english,

and others that I forgot :-(

**Comment by ninjagolloyd** [comment]
>**kaaleth wrote:**
>...and the 3rd radio box is blank.
This is also in English.


#What is this?

**Comment by kaaleth** [comment]
Does not work for me.

![image](http://s27.postimg.org/aknbrq7ab/Bez_tytu_u.png)

**Comment by ninjagolloyd** [comment]
Uh... That is what I said...

**Comment by Studio384** [comment]
Thanks for reporting. I myself also found a couple of missing translations, but it's hard to find them if you don't accidentical yfind them or are translating Luna. Thanks for reporting and they'll be added soon!

**Comment by kaaleth** [comment]
ninjagolloyd said:

> Uh... That is what I said...

I remember that function and it means "Automatically enable night mode (23:00-6:00)" or something smilar :)

**Comment by Studio384** [comment]
If you know more, please add them to this ticket (prefer with a checkbox in front of them to check them off). I just want to note that some of these are supposed to be the way they are, like "BackstageColor". This is simply due to development.

**Comment by ninjagolloyd** [comment]
√ guest

**Comment by ninjagolloyd** [comment]
Um how do you do the check

**Comment by ninjagolloyd** [comment]
Welcome, guest

**Comment by Studio384** [comment]
That's supposed to be like that, and something we won't fix. The final release should loop through a couple of languages to say "Welcome" or "Welkome back" or "Hello". ;)

**Comment by kaaleth** [comment]
Little update.

PS I have not touched the boxes ;)

**Comment by Studio384** [comment]
Thanks, I'll add them soon.

**Comment by kaaleth** [comment]
Little refresh.

**Comment by Studio384** [comment]
Hey, I'm working on the update system, need some time. ;)

**Comment by kaaleth** [comment]
That's ok! :)

I just added some another untranslated texts.

**Comment by Studio384** [comment]
Great, once again thanks for the contribution, I'll add them soon.

**Comment by Studio384** [comment]
Thanks for reporting them, we've fixed them and will soon push this commit. Report here more if you find them. ;)

**Comment by kaaleth** [comment]
Everything looks fine, but... after language is changed, the "Night mode" strings are still in english.
![image](http://i.imgur.com/nMKw7NC.png)

**Comment by Studio384** [comment]
New language strings have yet to be added.
