### ISSUE TITLE
Unexpected T_STRING in MO.php

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1293]
Today I tried to install the preview and dev branch, but they weren't be able...

```
Parse error: syntax error, unexpected T_STRING in /home/dstawick/public_html/include/pomo/MO.php on line 9
```

**Comment by ninjagolloyd** [comment]
It works fine for me.
Try
# __*LunaUpdateDrive*__
I use it and it works.

**Comment by Studio384** [comment]
LunaUpdateDrive contains unsupport and unreliable builds that have some broken features. I do not recommand to use these. Anyway, I'll look into it.

**Comment by kaaleth** [comment]
I have noto used LunaUpdateDrive...

**Comment by ninjagolloyd** [comment]
It works for me Yannick
Actually a bit better..?

**Comment by kaaleth** [comment]
Ok, I changed PHP 5.4 into 5.5. Now, works fine.

**Comment by ninjagolloyd** [comment]
Lol

**Comment by kaaleth** [comment]
Please. don't spam when you don't know the answer...

**Comment by Studio384** [comment]
@kaaleth Sadly we support PHP 5.2, 5.3 and 5.4 too.

**Comment by CaerCam** [comment]
Caused by the POMO library using namespaces, not supported by PHP 5.2, so we either update the requirements to PHP 5.3 or remove namespaces from the lib. I'm betting we'll go with the second, in which case I'll submit a pull-request :)

**Comment by kaaleth** [comment]
Thanks for explanation.

**Comment by Studio384** [comment]
Though one, I wanted to drop support for PHP 5.2 as soon as it hits 10% market share, it now has 14,7%... It had a market share of 15,4% last month.

**Comment by ninjagolloyd** [comment]
Yes. Most hosts update frequently, and it is *__extremely__* easy to update locally.

**Comment by CaerCam** [comment]
That's right, but it seems dôme hosts still put 5.2 as default, requiring the user to specifically select a more recent version. I've heard of hosts allowing version selection only with paid upgrade. I guess that's why a lot of softwares stillsupport 5.2 despite its obsolescence. Anyways, I'll fix this for 5.2 so we don't have to bother.

**Comment by ninjagolloyd** [comment]
Some recommendations: [Gwiddle]<http://gwiddle.co.UK>. or [x10]<http://x10hosting.com>
Both are completely free and have free new php (I use both.)

**Comment by Studio384** [comment]
@ninjagolloyd - Please stay on topic, discuss the ticket, not some unrelated free hosts.

And no, not even close to all "hosts update frequently". Almost 50% of the world's hosts is using an unsupported version of PHP (5.3 and lower).

**Comment by ninjagolloyd** [comment]
Yes. And I found really good hosts that work perfectly, and I was recommending them because they are easy and fast and good and free.

**Comment by CaerCam** [comment]
Removed namespaces. I don't have a PHP 5.2 server at hands right now so this will require more tests, though.

**Comment by kaaleth** [comment]
My localhost uses PHP 5.2. After upgrade, looks fine.

**Comment by Studio384** [comment]
Thanks for the fix @CaerCam!

**Comment by CaerCam** [comment]
You're welcome :)
