### ISSUE TITLE
HTML/BBcode in forum description

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1294]
Any solution to add some html or bbcode tags into forum's description?

**Comment by Studio384** [comment]
You can use HTML in the boards description.

**Comment by kaaleth** [comment]
Does not work for me.

I have made some changes in Luna theme, but I left some original code (objects/forum.php), like:

```
html

	 <div class="list-group-item roweven <?php echo $item_status ?>" data-toggle="tooltip" data-placement="left" title="<?php echo ''.$cur_forum['num_topics'].' postów '?>	<?php echo ''.$cur_forum['num_posts'].' tematów'?>">
	 <a href="viewforum.php?id=<?php echo $cur_forum['fid'] ?>"><b><?php echo luna_htmlspecialchars($cur_forum['forum_name']) ?></b></a> <span class="pull-right"><small><?php echo $last_post ?></small></span> <br /> <?php echo $forum_desc ?>
</div>
```

The result is:

![demo](http://i.imgur.com/MF1u0uH.png)

I think I missed something. Could you help me, please?

**Comment by Studio384** [comment]
Ow, I'm sorry, I confused it with the Board description. My bad. I'll add it as a planned feature for Luna 1.1.

**Comment by kaaleth** [comment]
Thanks. Can't wait for solution!

**Comment by Studio384** [comment]
You can fix this by removing the luna_htmlspecialchars() function from the forum description. This will allow all HTML in it to render.

**Comment by kaaleth** [comment]
but **luna_htmlspecialchars()** relates to forum name, not forum description.

**Comment by Studio384** [comment]
It's also used on forum descriptions. You can find it in draw_functions.php on line 354. This has been changed in Luna 1.1 now.
