### ISSUE TITLE
Allow themes to opt out of night mode and accents

### ISSUE THREAD

**Issue by ListenerJubatus** [GetLuna/Luna#1322]
I had to partially go back to the default theme after my upgrade to 1.1, because, in the midst of porting my custom theme to use Fifteen as its child, I discovered that due to the new header meta code, all themes using it are forced into supporting accents and night mode. This might not be desirable in some themes, which may intentionally design themselves with a specific color scheme in mind (such as to match a website).

Personally, I think there should be some sort of "switch" in information.php for enabling these features, so themes can individually

**Comment by Studio384** [comment]
Luna 1.1.1 will allow you to disable custom accent colors and night mode completely.
