### ISSUE TITLE
"Topic" and "Post" and "User online" can't translate

### ISSUE THREAD

**Issue by ramtinak** [GetLuna/Luna#1330]
Hi, I was wondering to know why "Topic" and "Post" can't be translate? see this picture>
http://dl.ramtinak.ir/uploads/a104898d35791.png

all words is in Persian except "Topic" and "Post".
in the footer "user/users online" can't be translated to. I translate these word("user/users online") in a php file that can't remember right now to tell you.

I translated all words on the Language file so it can't be my translation.

Please give me a solution to translate "Topic" and "Post". I couldn't find it.

**Comment by Studio384** [comment]
Which version of Luna are you using?

**Comment by ramtinak** [comment]
the last one, v1.1.1 ( http://modernbb.be/cnt/get.php?id=103 )

**Comment by Studio384** [comment]
I'm terribly sorry, lost track of this issue. I'll look into it for the next release.
