### ISSUE TITLE
can not send any post in mobile version

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1342]
Hi,

I can not send any post from mobile version on the official luna forum. Error page is: Bad http_referer.

**Comment by rolfpancake** [comment]
There is no mobile version. It's just responsive. (You can see this by changing the size of your browser window to the size of a smartphone)
This is also not an issue which belongs to github. I can't reproduce the error on my own site. Maybe you should discuss this topic on the forum:
http://forum.getluna.org/viewforum.php?id=2

**Comment by kaaleth** [comment]
Doh, I know that and I mean mobile grid...  Let me think... How to send post from mobile device when I have no access to my PC...

**Comment by CaerCam** [comment]
That's not unknown to me, the referrer "safety" check is a pain anyway. I implemented the nonce API precisely to get rid of this part, just didn't have enough time to make the transition yet.

**Comment by Studio384** [comment]
It's a safety feature and means that you probably visited the website from the wrong URL. Make sure to visit the board from forum.getluna.org and not getluna.org/forum. As @CaerCam said, we're working on kicking out this.

**Comment by CaerCam** [comment]
Maybe we could try this update, see how it works, then we can extend the nonce usage to the rest of the forum.
