### ISSUE TITLE
Unread forums in Night mode are illegible on Fifteen

### ISSUE THREAD

**Issue by ListenerJubatus** [GetLuna/Luna#1358]
Personally, they should be marked in the accent color (or well, a shade of it) or a darker grey, but DEFINITELY not white, mainly because you can't even read it with how it is now.

![screen shot 2015-09-03 at 11 13 35 am](https://cloud.githubusercontent.com/assets/6346433/9665365/0cb9736a-522d-11e5-9cc8-8d7f16df2f30.png)

**Comment by Studio384** [comment]
Thanks for report.
