### ISSUE TITLE
Fatal Error on Appearance

### ISSUE THREAD

**Issue by mohsennirouzad** [GetLuna/Luna#1364]
Hi friends,
I was testing appearance of theme "Sunrise" in Luna Cornflower Blue,
But when I choose Sunrise theme, If I goto appearance tab, I will take this error:

WampServer wrote
Fatal error: Call to a member function read() on a non-object in C:\wamp\www\Luna-luna-1.2-alpha.1\include\functions.php on line 1614
Call Stack
#	Time	Memory	Function	Location
1	0.0020	327000	{main}( )	..\appearance.php:0
2	0.1200	2185856	forum_list_accents( )	..\appearance.php:111
But when I use other themes (Sixteen,Fifteen and a Sixteen-based theme called "Ubuntu" written by myself) I never get this error and all things are normal ...
Luna Page in appearance tab:

Display settings
Theme settings: Allow users to set their own accent color.
Allow users to change the night mode settings.
Color:
Fatal error: Call to a member function read() on a non-object in C:\wamp\www\Luna-luna-1.2-alpha.1\include\functions.php on line 1614
Call Stack
#	Time	Memory	Function	Location
1	0.0020	327000	{main}( )	..\appearance.php:0
2	0.1200	2185856	forum_list_accents( )	..\appearance.php:111
Sorry, I can't attach a screenshot too, Can you if your internet speed be 4KB per second???!!!
How can I fix this error? Thanks a lot Yannick.

**Comment by Studio384** [comment]
This happens because the Appearance page apperantly ignores that Sunrise is a child of Fifteen and thus is supposed to use Fifteen's accent. Instead, it looks for accents in the Sunrise folder, but there are no accents there, so this causes this bug.

**Comment by mohsennirouzad** [comment]
Thanks Studio384, Thanks a lot to all Luna Developers to fix bug...
