### ISSUE TITLE
Terminology unification

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1368]
Since Luna 1.0, we've taken a run with terminology. We should unify the way we call things. I mean, are topics that are put on top of the forum list sticky topics, or pinned topics? And are it even topics, or threads? And how do you react on these threads? With posts or comments?

Point being, it is time for some unification, both on the front-end as back-end. These are the common 3 that need some attention:

Sticky -> Pinned
Topic -> Thread
Post -> Comment

**Comment by CaerCam** [comment]
I like Pinned/Thread/Comment. Seems more adequate now than the rather oldish alternative currently in use.

**Comment by Studio384** [comment]
I'm gonna be honest, this sounds like much less work than it actualy is.
