### ISSUE TITLE
Wrong email address

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1378]
Hello,

As I can see, Luna doesn't like my email address. I couldn't install my forum, because address always was wrong. My email is like: name.surname@domain.com . Moreover I can't update my profile on my forum. I am running 1.2 alpha 2.1.

**Comment by Studio384** [comment]
I'm investigating. For now, I'm not able to reproduce this issue, I will take a further look at it, though.

**Comment by Studio384** [comment]
Please provide additional information, I'm able to register with the given mail address and variations of it.

**Comment by kaaleth** [comment]
I can tell only I use WAMP server. I been trying to install forum on my localhost and luna always shows me error "invalid email".

**Comment by Studio384** [comment]
I'm very happy to tell you that this issue will be fixed in Luna 1.2.4 as we've found a way to replicate (what we think) is the issue. :)
