### ISSUE TITLE
Wrong error shown when adding a user with long name

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1394]
If a user shall be created via the 'add user'-tool and the username is longer than allowed (a hint would be great, how long it can be) a message about password length appears.

![longest_name_1](https://cloud.githubusercontent.com/assets/9326192/10495677/56cf54d2-72bd-11e5-8bd5-c6e7b302857b.png)

![longest_name_2](https://cloud.githubusercontent.com/assets/9326192/10495679/5a59388e-72bd-11e5-85c8-8ca8b45107ad.png)

**Comment by Studio384** [comment]
Please do not include your own tags in titles.
