### ISSUE TITLE
Long username can lead to overlapping effect in users profile

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1396]
A username too long for the profile page box leads to ignoring the borders.

![change_username](https://cloud.githubusercontent.com/assets/9326192/10495901/8606dc6a-72be-11e5-9d3c-731624528896.png)

**Comment by rolfpancake** [comment]
Same with the User title if is one single word

![user_title_one_word](https://cloud.githubusercontent.com/assets/9326192/10499219/5c8ddada-72cf-11e5-88dc-02d03573fa58.png)

**Comment by Studio384** [comment]
#1334
