### ISSUE TITLE
[Backstage] Long descriptions for reported comments lead to broken boxes

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1397]
If a user reports a comment a description must be given. There is no maximal length for this description so it could break the tables in backstage.

![report_spam](https://cloud.githubusercontent.com/assets/9326192/10496216/e74ff924-72bf-11e5-9ecd-ad7b1fb011fa.png)

**Comment by Studio384** [comment]
Threse is a maximum length for descriptions, just not for individual words or in this case string of characters. AGain ,not a bug.
