### ISSUE TITLE
Changing 'User title' for a admin-group leads to update error

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1398]
On setup of group options and permissions it is possible to change the 'User title' of a group, which overrides the user rank. If the title is changed an error is encountered that the group couldn't be updated.

Example

![group_rank_1](https://cloud.githubusercontent.com/assets/9326192/10496363/bed99ada-72c0-11e5-8a13-8a279de22421.png)

Error

![group_rank_2](https://cloud.githubusercontent.com/assets/9326192/10496368/c31ef02c-72c0-11e5-95ca-8b6a505bdcea.png)

**Comment by Studio384** [comment]
Don't include tags like that in titles, that is just anoying to read.
