### ISSUE TITLE
[Announcement] Breaking the displayed box if title or content is a word which could not fit

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1399]
Long titles or texts of an announcement can lead to overlapping of the box borders.

![announcement_too_long](https://cloud.githubusercontent.com/assets/9326192/10496547/a996c0b6-72c1-11e5-87ed-bbf7437dfa13.png)

**Comment by Studio384** [comment]
If anyone can give me valid wordt that will ever be that long, I'll fix this, but for as long as that not happens, this is something everything will do wrong...
