### ISSUE TITLE
[Sixteen] Highlighting soft deleted comments

### ISSUE THREAD

**Issue by rolfpancake** [GetLuna/Luna#1405]
With Fifteen comments which are soft deleted are getting a light yellow highlighting.
This should be adopted for Sixteen. Maybe with a light red, because it is more intuitive for deleting things to use a red tone.

![soft_delete](https://cloud.githubusercontent.com/assets/9326192/10498479/d869bcf4-72cb-11e5-9e84-5189ad0bfa5f.png)

**Comment by Studio384** [comment]
#1334
