### ISSUE TITLE
Original english.po file is corrupted

### ISSUE THREAD

**Issue by kaaleth** [GetLuna/Luna#1408]
I would like to upgrade my language pack but I cannot sync all changes from original english "po" file. Moreover, english.po contains only 249 words against ~1000. What is wrong?

As my program, I use PoEdit and Luna 1.2.5038.

**Comment by Studio384** [comment]
This is fixed in the final version.

**Comment by kaaleth** [comment]
Hmmm...

![error](https://cloud.githubusercontent.com/assets/3610174/10562716/fe8d92c0-7569-11e5-9072-555f6c3cad0f.png)

**Comment by Studio384** [comment]
Duplicates have been removed already. If you download the language files from the lunadev branch, it should work. Sorry for these issues.

**Comment by kaaleth** [comment]
So... What am I doing wrong?

![1](https://cloud.githubusercontent.com/assets/3610174/10563352/a57351de-7587-11e5-8a16-df0ed5cbe84d.png)
![2](https://cloud.githubusercontent.com/assets/3610174/10563353/a5750f9c-7587-11e5-9591-e2199e90c94d.png)

**Comment by kaaleth** [comment]
@Studio384

**Comment by Studio384** [comment]
Did you remove the duplicates from your translation?

**Comment by kaaleth** [comment]
I didn't anything. Would you like to give me some tips, please? I use PoEdit.

**Comment by Studio384** [comment]
Open the luna.po file in a text editor and visit the lines in the error message, then simply remove them.

**Comment by kaaleth** [comment]
Hmm, I don't know what am I doing wrong. Could you help me, please?

There are translation files:
https://onedrive.live.com/redir?resid=CE96150D87321FBE!156887&authkey=!ADO0scHKKRE9U1g&ithint=file%2cpo

**Comment by kaaleth** [comment]
@Studio384

**Comment by Studio384** [comment]
I'm terribly sorry, I lost track of this. However, I've been taking a look at your file and made some updates to the configurations of it and updated the contents of it (there are a couple of new stirngs in there now that you might want to take a look at). Here you go:

https://onedrive.live.com/redir?resid=1573A6472EDD1166!352818&authkey=!AO8K1EnLfu3CQzY&ithint=file%2cpo

**Comment by kaaleth** [comment]
Thank you very much! Now I need to finish translate :) . I saw some strings I have to translate once again but that's not problem. Thanks.

**Comment by Studio384** [comment]
That's because we updated a lot of them, your file seemed to be very out-of-date.
