### ISSUE TITLE
Text size markup

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1436]
In earlier versions of ModernBB, we introduced the [size] tag already. Out of that, we could only conclude that it was a terrible idea: giving users more freedom in the style of their comments will result in a mess. So for the reintroduction of the size-tag, we need to think twice. This is the proposal:

#### Optional
First of all, the size-tag won't be parsed by the parser by default and needs to be enabled by the admin in the Backstage (this is a global setting, affecting everyone). For new installations and upgrades, this will be disabled by default when upgrading to Luna 1.3, for future upgrades, the setting will obviously remain as set by the admin.

#### Tag's to use within
To limit the 'bad behavior' of users, we'll limit the tags that can be used within the size-tag to just a couple:

- b, i, s, u and ins
- sub and sup
- color
- url and email

On other tags, this simply won't have any influence or will result in bad readability (lists for example).

#### Tag's the size-tag can be used in

- b, i, s, u and ins
- sub and sup
- color
- url and email
- quote

As quotes can contain full posts, they're an obvious choise to allow sizeing. Other tag are allowed because of reversed support.

#### Tag functionality
Another limit set on the tag will be the spanwidth of the size it can actually hold. This will be given in percent to the default font size in that particular scenario (so it depends on the used theme). This will be in a margin of 50-250%.

The size-tag will be documented in the Help-section if enabled but won't be part of the editor toolbar.

**Comment by Quy** [comment]
We implemented this and it was a hot mess. We had members using the largest font size possible. It made it impossible to read with the different font sizes being used.

**Comment by benjawi** [comment]
That's why you set limits - make it a percentage and have it 50% either way or something. People abuse it and have all their posts huge or small, instead of using it responsible, put it as a rule that they can't and will result in warnings leading to a ban eventually. When members use it right, it's a good thing to have.

**Comment by Quy** [comment]
I can't recall exactly, but it was limited to 3 to 5 sizes. Of course, they selected the largest size and colorized. I prefer not to monitor/deal with potential abuse on this one. Why not use the [h] tag in this case?

**Comment by Studio384** [comment]
I'm planning to keep this as far away from users, it won't be in the toolbar, and I'm planning to not documentate it in Help either. For Luna 2.0, I'm looking into per-tag based permissions for each group with this one disabled by default (which means that upgrades will disable it too) for normal user groups.
