### ISSUE TITLE
{Luna 1.2 beta 1} Wrong background colour in announcement section

### ISSUE THREAD

**Issue by mohsennirouzad** [GetLuna/Luna#1441]
Get this file: http://up.20script.ir/file/46ff-screenshots.rar

You can see in screenshot 1, I selected that my board show a announcement in green colour ( success )
But if you take a look about screenshot 2, You can see that text colour and background colour are nearly white ( When it most be black on green - success ), That's why I spent many time to just find the announcement section! ( above the Recent activity! )

I glad I could explain it to you!
And a really small thing I saw in Luna.I got Luna 1.3 beta 1, but in backstage-->about.php I see this:
Denim       1.3 Preview 6

**Comment by Studio384** [comment]
This bug was fixed in the latest commit to the branch. Beta 1 is indeed labeled as Preview 6, beta 2 will be labeled as Preview 7 in the about section.
