### ISSUE TITLE
No value for Comments in About user

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1442]
See http://forum.getluna.org/profile.php?id=3765

**Comment by Studio384** [comment]
Mmmm. Weird, some users show it, others don't. Any idea yourself what this might be?

**Comment by Quy** [comment]
`$user_personality[] = '<b>'.__('Comments', 'luna').':</b> '.$comments_field = forum_number_format($user['num_comments']);`

Remove `$comments_field =`???

**Comment by Studio384** [comment]
That doesn't solve it. At some point Luna puts a NULL in the database, but I have no clue where or why that happens.
