### ISSUE TITLE
Time not vertically aligned with text

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1445]
See screenshot:
https://www.dropbox.com/s/bw7poi0mn0903uf/notifications.jpg?dl=0

**Comment by Studio384** [comment]
Not sure what causes this... It works fine in Edge, IE or Chrome. Seems to happen only in Firefox.

**Comment by Studio384** [comment]
Seems to be an issue that slipped in between Luna 1.2.4 and Luna 1.3 Preview 1... I'm looking into this, but it might not be fixed for RC2, will be fixed in final release.
