### ISSUE TITLE
Notifications sort order

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1456]
In the drop down, it is ascending, but in the Notifications page, it is descending.

**Comment by Quy** [comment]
The notifications page is not sorted in the same order as the notifications flyout.

**Comment by Studio384** [comment]
Dammit, I forgot that reversing the order in the fly-out also reverses the order on the page...

**Comment by Studio384** [comment]
@CearCam

**Comment by Studio384** [comment]
Not sure if editing a wrong tag actually creates a new notification here, so just in case: @CaerCam. :)

**Comment by Studio384** [comment]
Screw it, this is fixed in Luna 2.0, that'll have to do...

**Comment by Studio384** [comment]
Porting it is...

**Comment by Studio384** [comment]
Refer #1523
