### ISSUE TITLE
Move meta tags

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1457]
I don't know the specifics, but Bootstrap recommends having the meta tags come first. Also, add `shrink-to-fit=no`.
```
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
```

**Comment by Studio384** [comment]
Not sure if that's an requirement to put metals first. Will require some research...

**Comment by Studio384** [comment]
Hm. As far as I can find, there is no technical reason to put meta tags first. Anyway, I'll add `shrink-to-fit=no`.

**Comment by Studio384** [comment]
Reference #1463
