### ISSUE TITLE
Login modal is large on search page

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1463]
On an iPad, when logging in from the search page, the login modal is displayed large.

**Comment by Studio384** [comment]
Which theme (and which search page (normal, advanced, results, etc.)?

**Comment by Quy** [comment]
Fifteen. On the default search page `http://forum.getluna.org/search.php`. Tested on other sites using Luna.

**Comment by Studio384** [comment]
As I don't have access to an iPad (or any other iOS device) this is kinda hard to figure out.

**Comment by Quy** [comment]
I will investigate this later today and let you know.

**Comment by Quy** [comment]
This is affected on any pages where the content doesn't fill the entire page. The browser zooms in before displaying the modal. I think moving the meta tags as mentioned in Bootstrap will fix the issue:
```
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
```

**Comment by Studio384** [comment]
Alright, I've applied the fix to our main board, can you try it and confirm if it fixed it?

**Comment by Quy** [comment]
Sorry it didn't. I am not sure why it is doing it. Maybe a browser bug.

**Comment by Studio384** [comment]
Is this issue still there on the latest version of iOS?

**Comment by Quy** [comment]
It is no longer an issue using iOS 9.2.1.
