### ISSUE TITLE
No Subscribe link for forums

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1464]
It is not possible to subscribe to a forum, since there isn't a Subscribe link.

**Comment by Studio384** [comment]
There is one in your profile under "About user".

**Comment by Quy** [comment]
Why would it be under "About user"?

I expect to go to a forum. In the left side bar, there would be a Subscribe link.

**Comment by Studio384** [comment]
My bad, I commented the wrong comment in the other issue.

> That's actually intentional, as I'm not sure if it is still needed. The whole system is left in place until further notice and to allow people that already subscribed to continue to receive messages, but I'm not sure this will be maintained going into Luna 2. I consider this feature deprecated.
