### ISSUE TITLE
No Show Subscriptions button in profile

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1465]
There is no button for `Show subscriptions` to search for threads I have subscribed to.

**Comment by Studio384** [comment]
That's actually intentional, as I'm not sure if it is still needed. The whole system is left in place until further notice and to allow people that already subscribed to continue to receive messages, but I'm not sure this will be maintained going into Luna 2.

**Comment by Studio384** [comment]
My bad, I commented the wrong comment in the other issue.

> There is one in your profile under "About user".

**Comment by Quy** [comment]
OK it is only accessible to admins/mods:
```
	if ($luna_user['is_admmod'] && $luna_config['o_thread_subscriptions'] == '1')
		$quick_searches[] = '<a class="btn btn-primary btn-sm" href="search.php?action=show_subscriptions&amp;user_id='.$id.'">'.__('Show subscriptions', 'luna').'</a>';
```

**Comment by Studio384** [comment]
I shall make it available to the user self too.
