### ISSUE TITLE
Night mode on default theme has poor color contrast, hard to read

### ISSUE THREAD

**Issue by ListenerJubatus** [GetLuna/Luna#1501]
![poor contrast](https://cloud.githubusercontent.com/assets/6346433/13608282/b58f53c2-e519-11e5-803f-541f595aaa88.PNG)

On the current 1.4 build, the Night mode color scheme has very poor contrast in its choices of colors. It's actually hard to read the text on the forum listing because of the shades of gray used, in combination with the default accent color and thin font weights.

I played around with the inspector and picked some alternate Night mode colors that are more legible. I personally think these would also suit night mode better on the default theme, as they actually are a bit darker than what we have now.

![different colors](https://cloud.githubusercontent.com/assets/6346433/13608432/5f4d644e-e51a-11e5-9389-1a389a806fa7.png)

**Comment by Studio384** [comment]
Yeah, I also had my doubts about the color scheme and that it should be slightly darker, I'll take your color pallet for a spin. :)

**Comment by Studio384** [comment]
I have just pushed an update to our main board with an updated color scheme, please review and let me know what you think about it.

**Comment by ListenerJubatus** [comment]
It's a little better, but I still think the colors on the forum list should be inverted (make current hover color the BG, and go lighter on hover instead)

**Comment by Studio384** [comment]
I've applied your feedback, take another look. :)
