### ISSUE TITLE
Timestamp displays below notificaiton text

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1536]
See screenshot:
https://www.dropbox.com/s/bw7poi0mn0903uf/notifications.jpg?dl=0

**Comment by Studio384** [comment]
What browser is that?

**Comment by Quy** [comment]
Firefox 45.0.1 Windows 8.1

**Comment by Quy** [comment]
Now it is happening on this page:
http://localhost/projects/luna/notifications.php

**Comment by Studio384** [comment]
Dammit.
