### ISSUE TITLE
Can't change Avatar Settings

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1540]
After changing any Settings or trying to change Avatar Settings in nightly Avatars are disabled and the directory is null.

**Comment by Studio384** [comment]
I'm not experiencing this issue in the development branch. I've pushed some changes to nightly, try again and let me know if it fixes anything.

**Comment by Scrumplex** [comment]
I cloned the branch nightly and that was not fixed.

**Comment by Scrumplex** [comment]
As far as I can see in the [features.php](https://github.com/GetLuna/Luna/blob/nightly/backstage/features.php), there is no check for the POST avatars so it won't be saved.

**Comment by Studio384** [comment]
Should be fixed now.
