### ISSUE TITLE
Drop fa fa-fw fa-

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1554]
If you are not familiar with Font Awesome, you may not know what `fa fa-fw fa-` is. You may want to drop the `input-group-addon`.

**Comment by Studio384** [comment]
Yeah, but on the other hand, perhaps that would make people type in as icon "fa fa-fw fa-list" for example while only "list" is required.

**Comment by Quy** [comment]
I can see that. You can check/reject if value contains space(s).

**Comment by Studio384** [comment]
I'm note sure that that's going to make much of a difference. There will always be the need to point out that ```fa fa-fw fa-``` is already being accounted for. You can't just say that "There are no spaces allowed in the icon name", you'll have to say that the other classes are already added, which would be useless in case it had to be replaced with the addon in my opinion.
