### ISSUE TITLE
Warning in install of Luna-2.0-alpha5

### ISSUE THREAD

**Issue by halojoy** [GetLuna/Luna#1558]
Warning: Division by zero in C:\Apache24\htdocs\luna\include\srand.php on line 106

**Comment by Studio384** [comment]
This should already be resolved in the version2.0 branch. Please test it with that version.

**Comment by halojoy** [comment]
I did test with version2.0.
It is the same warning.

**Comment by Studio384** [comment]
May I ask you if you could confirm whether or not the same issue happens with FluxBB (http://fluxbb.org)?

**Comment by halojoy** [comment]
I have  installed fluxBB 1.5.9 at my server.
This Warning was not happening with fluxBB.

For some reason there is a division with zero in both v2.0 and 2.0alpha5.
I wonder if Luna 1.3.1 is okay?

**Comment by Studio384** [comment]
Thanks for reporting.

**Comment by Studio384** [comment]
I've just pushed an update to the version2.0 branch, could you please test again?

**Comment by halojoy** [comment]
It is okay now.
You have fixed this issue. We may close it now.
