### ISSUE TITLE
Error deleting a comment 

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1573]
When deleting via moderating thread:

`C:\xampp\htdocs\projects\Luna\backstage\header.php on line 40`

Failed query:
`SELECT COUNT(id) FROM luna5_notifications WHERE viewed = 0 AND user_id = 2`

**Comment by Studio384** [comment]
I'm unable to reproduce this. Are there any additional steps required?

**Comment by Quy** [comment]
Go to a thread.
Click `Moderate`.
Click a checkbox.
Click `Delete` button.
