### ISSUE TITLE
Unrendered emojii

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1591]
Firefox 45.0.2 on Windows 8.1

https://www.dropbox.com/s/aexomyvpwby67l9/emojii.jpg?dl=0

Also, text is touching the left border.

**Comment by Studio384** [comment]
The text touching the border has already been fixed in the last revision on GitHub, thanks for the other report.

**Comment by Studio384** [comment]
Does Internet Explorer render the emoji correctly?

**Comment by Quy** [comment]
Same issue in IE 11.0.9600.18283.
