### ISSUE TITLE
Display issues on iPad

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1592]
See screenshots:
https://dl.dropboxusercontent.com/u/4284608/index.png (search button and login box)
https://dl.dropboxusercontent.com/u/4284608/contact.png (contact icon)
https://dl.dropboxusercontent.com/u/4284608/pagination.png
https://dl.dropboxusercontent.com/u/4284608/register.png (button)
https://dl.dropboxusercontent.com/u/4284608/research.png (search field and advanced button)
https://dl.dropboxusercontent.com/u/4284608/userlist.png (avatar)
https://dl.dropboxusercontent.com/u/4284608/thread.png (space above avatar)
https://dl.dropboxusercontent.com/u/4284608/stats.png (users online not aligned)

**Comment by Studio384** [comment]
Whut? Does Luna really look like that on an iPad? That's horrible.

**Comment by Quy** [comment]
Yes. I am on iOS 9.3.1.

**Comment by Studio384** [comment]
Gosh. I said "some", but it seems to ignore almost all of them.

And this looks still like that in beta 1 (or alpha 7 on our website)? Do you happen to know if iPhones also have this issue?

**Comment by Quy** [comment]
I just checked...yes on iPhone too.

**Comment by Studio384** [comment]
Any idea why this may be happening?

**Comment by Quy** [comment]
I don't. It is hard to troubleshoot on an iPhone/iPad since there isn't a developer tool. I will see if I can find out the issue.

**Comment by Studio384** [comment]
Do you happen to know if there are also issues with the Backstage?

**Comment by Quy** [comment]
Backstage is fine.

**Comment by Quy** [comment]
Look at the index screenshot, there is padding above the navbar and between the navbar and first run box. Maybe margin/padding is being added on an iPad/iPhone that could be causing the issue.

**Comment by Quy** [comment]
Found the culprit in `style.css` line 1331. 
```
:not(:first-child.editor) {
	margin-top: 10px;
}
```
