### ISSUE TITLE
Blank `Add forum` box after adding a forum on iPad

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1593]
After adding a forum, the `Add forum` box is blank. You have to click on the Board tab to load the page to see the content of the `Add forum` box.

Screenshot:
https://dl.dropboxusercontent.com/u/4284608/board.jpg

**Comment by Studio384** [comment]
What is wrong with iPads...

**Comment by Quy** [comment]
The alert `Your settings have been saved.` overlaps with the 1st panel heading.

**Comment by Studio384** [comment]
Thanks, I'll take a look at it.
