### ISSUE TITLE
Theme Not Working

### ISSUE THREAD

**Issue by nobeldwarf** [GetLuna/Luna#1597]
Sunrise theme inst working for Luna 2.0-rc. 1. When this theme is selected it makes the forum 500 error and can't be access again unless you reinstall the forums.

**Comment by Studio384** [comment]
I've noticed this issue myself too and am working on a fix. However, reinstallation isn't needed. Just go to your config cache file and change o_default_style to Fifteen, then open Settings > Theme and click save.
