### ISSUE TITLE
URL in email not there

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1599]
Hello there,
when someone registers in the forum, I will get en email notification, because I am in the mailing list.
The email looks like this:
```
User "*here was a name*" registered in the forums at https://forum.sprum.ml/

User profile: https://forum.sprum.ml/profile.php?id=*herewasanumber*

To administer this account, please visit the following page:
<admin_url>

--
Sprummlbot Mailer
(Do not reply to this message)
```
The `<admin_url>` is not replaced by Luna.

Kind regards

**Comment by Studio384** [comment]
This has been fixed in 2.0.1. Thanks for reporting!
