### ISSUE TITLE
No permission to reset password?

### ISSUE THREAD

**Issue by ListenerJubatus** [GetLuna/Luna#1606]
A user on my forum (upgraded to 2.0.1 from 1.3 recently) is reporting that they are unable to reset their password, as the URL given to reset states that "You do not have permission to access this page."

**Comment by Studio384** [comment]
By the way, I'm looking into this issue and I hope to deliver a fix for 2.0.2.

**Comment by Studio384** [comment]
Can you tell me if the reset url contain an user ID?

**Comment by Studio384** [comment]
Well... never mind. We've pinned down the issue and it will be taken care of in version 2.0.2. A release is set for the coming days.

**Comment by ListenerJubatus** [comment]
Okay, apparently there are still problems going on with password resets on my specific site.

Now the user is reporting that the randomly-generated password doesn't seem to be working.

**Comment by Studio384** [comment]
https://github.com/GetLuna/Luna/issues/1609

**Comment by Studio384** [comment]
Did they request a new link?
