### ISSUE TITLE
PHP Error after update

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1608]
After I updated to the latest commit there is an PHP error in the db_update.php. 

PHP Parse error: syntax error, unexpected '$db' (T_VARIABLE) in /var/www/forum/db_update.php on line 300 

Side notes: 
I merged from lunadev. 

My "update script": 
```
#!/bin/bash

rm -rf luna/
git clone --branch lunadev https://github.com/GetLuna/Luna.git luna
rsync -av luna/ forum/
chown -R www-data:www-data ./
rm forum/cache/*
rm forum/install.php

```

**Comment by Studio384** [comment]
Lunadev is not the stable branch, version2.0 is.
