### ISSUE TITLE
Inbox doesn't show all messages. 

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1610]
Hello there, 
I got an email from my forum, because someone sent a DM to me. I went to my inbox and it didn't show me that DM. 
One of my users also reported that to me. 

Kind regards 
Sefa E.

**Comment by Studio384** [comment]
Which version are you using?

**Comment by Scrumplex** [comment]
2.0.2

**Comment by Studio384** [comment]
Was it a PM to just you, or multiple people?

**Comment by Scrumplex** [comment]
So I got this email: http://image.prntscr.com/image/9a7826f2789047acb3e5642f16b06d43.png

But there is nothing similiar to that in tbe db

**Comment by Scrumplex** [comment]
Okay I found the problem. The user sent an email via the forum. He didn't use the inbox feature. I think the `Send EMail` feature should do the same as creating an inbox conversation.

**Comment by Scrumplex** [comment]
#1612
