### ISSUE TITLE
Random password not working

### ISSUE THREAD

**Issue by DoraKlikOpDora** [GetLuna/Luna#1636]
Hey,

Random password is not working (like if you have forgotten it and you request a new one)
Solution I found: Database is initialized in the activation_string as a 80-character varchar, but it has to  be a 128 varchar.

Work it out, I am sure many people will find it helpful.

**Comment by DoraKlikOpDora** [comment]
Made a pull request https://github.com/GetLuna/Luna/pull/1637 to fix

**Comment by Studio384** [comment]
Thank you very much, before I close this it will also have to be altered for new installations, I'll take care of that.

**Comment by Studio384** [comment]
Ref #1614
