### ISSUE TITLE
Automatically subscribe to participating threads

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1643]
Hey there, 
Many forums have the function to be subscribed automatically if you participate in a thread. I would love to have that in Luna. It should be optional for the user but should be enabled by default. 

Have a nice day and
Merry Christmas

**Comment by Studio384** [comment]
We've decided not to change the default behavior for Luna on this. You can set it in Profile > Settings > Contact > Subscriptions, but we're not going to tick that box by default.
